/*
SQLyog Ultimate v11.11 (64 bit)
MySQL - 5.5.5-10.4.8-MariaDB : Database - mutantes
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`mutantes` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;

USE `mutantes`;

/*Table structure for table `dna_records` */

DROP TABLE IF EXISTS `dna_records`;

CREATE TABLE `dna_records` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `adn` text DEFAULT NULL,
  `is_human` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb4;

/*Data for the table `dna_records` */

insert  into `dna_records`(`id`,`adn`,`is_human`) values (1,'asdsd','YES'),(2,'[ATGCGA, CAGTGC, TTATGT, AGAAGG, CCCCTA, TCACTG]','YES'),(3,'[ATGCGA, CAGTGC, TTATGT, AGAAGG, CCCCTA, TCACTG]','YES'),(4,'[ATGCGA, CAGTGC, TTATGT, AGAAGG, CCCCTA, TCACTG]','YES'),(5,'[ATGCGA, CAGTGC, TTATGT, AGAAGG, CCCCTA, TQACTG]','YES'),(6,'[ATGCGA, CAGTGC, TTATGT, AGAAGG, CCCCTA, TQACTG]','YES'),(7,'[ATGCGA, CAGTGC, TTATGT, AGAAGG, CCCCTA, TQACTG]','YES'),(8,'[ATGCGA, CAGTGC, TTATGT, AGAAGG, CCCCTA, TQACTG]','YES'),(9,'[ATGCGA, CAGTGC, TTATGT, AGAAGG, CCCCTA, TQACTG]','YES'),(10,'[ATGCGA, CAGTGC, TTATGT, AGAAGG, TQACTG]','YES'),(11,'[ATGCGA, CAGTGC, TTATGT, AGAAGg, CCCCTA, TQACTG]','YES'),(12,'[ATGCGA, CAGTGC, TTATGT, AGAAGG, CCCCTA, TCACTG]','YES'),(13,'[ATGCGA, CAGTGC, TTATGT, AGAAGG, CCCCTA, TCACTG]','YES'),(14,'[]','NO'),(15,'[ATGCGA, CAGTGC, TTATGT, AGAAGG, CCCCTA, TCACTG]','YES'),(16,'[ATGCGA, CAGTGC, TTATGT, AGAAGG, CCCCTA, TCACTG]','YES'),(17,'[ATGCGA, CCGTGC, TTATGT, AGAAGG, CCCCTA, TCACTG]','YES'),(18,'[ATGCGA, CCGTGC, TTATGT, AGAAGG, CTCCTA, TCACTG]','NO'),(19,'[ATGCGA, CAGTGC, TTATGT, AGAAGG, CCCCTA, TCACTG]','YES');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
